projrct/new/project/credentials/urls.py
from . import views
from django.urls import path,include

app_name='empapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:emp_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

projrct/new/project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('credentials.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projrct/new/project/credentials/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    name=models.CharField(max_length=250)
    email=models.CharField(max_length=250,unique='')
    address=models.TextField()
    img=models.ImageField(upload_to='pics')
    desig=models.CharField(max_length=250)

    def __str__(self):
        return self.name

projrct/new/project/credentials/forms.py
from django import forms
from .models import Employee
class EmpForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields=['name','email','address','img','desig']

projrct/new/project/credentials/views.py
from django.shortcuts import render, redirect
from . models import Employee
from . forms import EmpForm
# Create your views here.
def index(request):
    movie=Employee.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)


def detail(request, emp_id):
    movie = Employee.objects.get(id=emp_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name',)
        email = request.POST.get('email',)
        address = request.POST.get('address',)
        img = request.FILES['img']
        desig=request.POST.get('desig')
        movie=Employee(name=name,email=email,address=address,img=img,desig=desig)
        movie.save()


    return render(request,'add.html')


def update(request,id):
    movie=Employee.objects.get(id=id)
    form=EmpForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Employee.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

projrct/new/project/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter name"><br>
    <input type="email" name="email" placeholder="Enter email"><br>
    <input type="text" name="address" placeholder="Enter address"><br>
    <input type="file" name="img"><br>
    <input type="text" name="desig" placeholder="Enter designation"><br>
    <input type="submit">


</form>
{% endblock %}

projrct/new/project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>


{% block body %}
{% endblock %}

</body>
</html>

projrct/new/project/templates/delete.html
<form method="post">
    {% csrf_token %}
    do you want to delete this employee?
    <input type="submit">

</form>

projrct/new/project/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
<div class="col-md-6">
    <h6><{{movie.name}}</h6>
    <h6>{{movie.email}}</h6>
    <h6>{{movie.adress}}</h6>
    <h6>{{movie.desig}}</h6>
    <a class="btn btn-warning" href="{% url 'empapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'empapp:delete' movie.id %}">delete</a>

</div>
    </div>
</div>
{% endblock %}

projrct/new/project/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>

projrct/new/project/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
        {% for i in movie_list %}

  <img  src="{{i.img.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.email}}</p>
      <p class="card-text">{{i.address}}</p>
      <p class="card-text">{{i.desig}}</p>



    <a href="{% url 'empapp:detail' i.id %}" class="btn btn-primary">details</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>


</body>
</html>